import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader } from "./ui/card";
import { Button } from "./ui/button";
import { cn } from "../lib/utils";
import playerImage from "../../public/ak.jpg";
export const CardPlayer = ({ playername, recave, kill, rebuy, outOfGame, }) => {
    return (_jsxs(Card, { className: cn("w-full max-w-[130px] mx-auto", "aspect-[3/5]", "bg-gradient-to-b from-slate-900/90 via-slate-900/80 to-slate-900/95 backdrop-blur-md", "border border-amber-400/20", "shadow-[0_0_15px_-3px_rgba(245,158,11,0.15)]", "overflow-hidden", "transition-all duration-300", "hover:shadow-[0_0_25px_-5px_rgba(245,158,11,0.25)]", "hover:scale-[1.02]", "relative"), children: [_jsx("div", { className: "absolute inset-0 z-0", children: _jsxs("div", { className: "w-full h-full bg-slate-800/50", children: [_jsx("img", { src: playerImage, alt: "Card background", className: "w-full h-full object-cover opacity-60" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-slate-900 via-slate-900/80 to-transparent" })] }) }), _jsxs("div", { className: "relative z-10 h-full flex flex-col ", children: [_jsx(CardHeader, { className: cn("p-1.5 space-y-0", "text-shadow-md", "border-b border-amber-400/10", "bg-gradient-to-r from-amber-500/10 via-slate-800/80 to-slate-800/80"), children: _jsx("h3", { className: cn("font-['DS-DIGI'] text-base text-center", "text-shadow-md", "text-xl sm:text-xl", "text-amber-400 tracking-wide", "truncate"), children: playername }) }), _jsx("div", { className: "flex-1 flex items-center justify-center p-1", children: _jsxs("div", { className: "space-y-1 w-full", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-amber-400/80 text-lg", children: "Recaves" }), _jsx("span", { className: "font-['DS-DIGI'] text-amber-400 text-lg", children: recave })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-amber-400/80 text-lg", children: "Kills" }), _jsx("span", { className: "font-['DS-DIGI'] text-amber-400 text-lg", children: kill })] })] }) }), _jsxs(CardContent, { className: cn("p-2 space-y-1.5", "bg-gradient-to-t from-slate-900/95 to-transparent"), children: [_jsx(Button, { variant: "outline", size: "sm", onClick: rebuy, className: cn("w-full h-7 text-sm font-['DS-DIGI']", "rounded-[5px]", "text-lg", "border-amber-400/20 hover:border-amber-400/40", "bg-amber-500/5 hover:bg-amber-500/10", "text-amber-400 hover:text-amber-300", "relative z-20"), children: "Recave" }), _jsx(Button, { variant: "outline", size: "sm", onClick: outOfGame, className: cn("w-full h-7 text-sm font-['DS-DIGI']", "border-red-400/20 hover:border-red-400/40", "text-lg", "text-shadow-lg", "rounded-[5px]", "bg-red-500/5 hover:bg-red-500/10", "text-red-500 hover:text-red-300", "relative z-20"), children: "Elimin\u00E9" })] })] })] }));
};
export default CardPlayer;
