import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
export const PlayerRanking = ({ players, playerScores, selectedPlayers, handlePlayerSelect }) => {
    const navigate = useNavigate();
    const handlePlayerClick = (playerId) => {
        navigate(`/player/${playerId}`);
    };
    return (_jsxs("div", { className: "min-h-screen bg-slate-900 p-5", children: [_jsx("h1", { className: "text-3xl font-bold text-amber-400 mb-6", children: "Player Rankings" }), _jsx("div", { className: "overflow-hidden rounded-[5px] border border-amber-400 bg-slate-900 shadow-[0_0_20px_rgba(251,191,36,0.1)]", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { className: "px-3 py-3 text-left text-sm font-semibold bg-blue-900/90 text-amber-400 border-b border-amber-400", children: "Select" }), _jsx("th", { className: "px-3 py-3 text-left text-sm font-semibold bg-blue-900/90 text-amber-400 border-b border-amber-400", children: "Rank" }), _jsx("th", { className: "px-3 py-3 text-left text-sm font-semibold bg-blue-900/90 text-amber-400 border-b border-amber-400", children: "Player" }), _jsx("th", { className: "px-3 py-3 text-left text-sm font-semibold bg-blue-900/90 text-amber-400 border-b border-amber-400", children: "Points" }), _jsx("th", { className: "px-3 py-3 text-left text-sm font-semibold bg-blue-900/90 text-amber-400 border-b border-amber-400", children: "Rebuys" })] }) }), _jsx("tbody", { children: players
                                .sort((a, b) => (playerScores[b.id]?.points || 0) - (playerScores[a.id]?.points || 0))
                                .map((player, index) => (_jsxs("tr", { className: "hover:bg-blue-900/80 transition-colors cursor-pointer", onClick: () => handlePlayerClick(player.id), children: [_jsx("td", { className: "px-3 py-3 text-sm text-amber-400 border-b border-amber-400/20", onClick: (e) => e.stopPropagation(), children: _jsx("input", { type: "checkbox", checked: selectedPlayers.some(selectedPlayer => selectedPlayer.id === player.id), onChange: () => handlePlayerSelect(player.id), className: "h-4 w-4 rounded border-amber-400 text-amber-600 focus:ring-amber-500" }) }), _jsx("td", { className: "px-3 py-3 text-sm text-amber-400 border-b border-amber-400/20", children: index + 1 }), _jsx("td", { className: "px-3 py-3 text-sm text-amber-400 border-b border-amber-400/20", children: player.name }), _jsx("td", { className: "px-3 py-3 text-sm text-amber-400 border-b border-amber-400/20", children: playerScores[player.id]?.points || 0 }), _jsx("td", { className: "px-3 py-3 text-sm text-amber-400 border-b border-amber-400/20", children: playerScores[player.id]?.rebuys || 0 })] }, player.id))) })] }) })] }));
};
