name: Build and Push Docker Images Poker

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3  
    
     - name: Create and use Buildx builder
       run: docker buildx create --use

     - name: Log in to Docker Hub
       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

     - name: Build and Push Frontend Docker image
       run: |
         docker buildx build --platform linux/arm64 \
           --build-arg VITE_REACT_APP_CLERK_PUBLISHABLE_KEY="${{ secrets.VITE_REACT_APP_CLERK_PUBLISHABLE_KEY }}" \
           --build-arg VITE_WEBSOCKET_URL="${{ secrets.VITE_WEBSOCKET_URL }}" \
           --no-cache -t pablohassan/poker_frontend_app:02 \
           -f ./src/Dockerfile --push .

     - name: Build and Push Backend Docker image
       run: |
         docker buildx build --platform linux/arm64 \
           --no-cache -t pablohassan/poker_backend_app:04
            \
           -f ./src/backend/Dockerfile --push .