name: Build and Push Docker Images Blog Sagesse 

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        # Checkout the repository
     - name: Checkout repository
       uses: actions/checkout@v4

          # Set up Docker Buildx this is required to build multi-arch Docker images here in arm version below 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3  
    
            # Create and use a Buildx builder (only needs to be done once even if i have multiple images to build)
     - name: Create and use Buildx builder
       run: docker buildx create --use

        # Log in to Docker Hub
     - name: Log in to Docker Hub using specic token generated for this repo and and dockerhub username
       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        # Build and push the Frontend Docker image for ARM64
     - name: Build and Push Frontend Poker Docker image
       run: |
         docker buildx build --platform linux/arm64 \
           --build-arg VITE_REACT_APP_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_REACT_APP_CLERK_PUBLISHABLE_KEY }} \
           --build-arg VITE_WEBSOCKET_URL=${{ secrets.VITE_WEBSOCKET_URL }} \
           -t pablohassan/poker_frontend_app:01 \
           -f ./src/Dockerfile --push .

        # Build and push the Backend Docker image for ARM64
     - name: Build and Push Backend Docker image
       run: |
         docker buildx build --platform linux/arm64 \
          -t pablohassan/poker_backend_app:01 \
          -f ./src/backend/Dockerfile --push .